// Alert Types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth Types
export const START_LOGIN = 'START_LOGIN';
export const START_REGISTER = 'START_REGISTER';
export const START_LOGOUT = 'START_LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// Bourbon Types
export const GET_PAGINATED_SUCCESS = 'GET_PAGINATED_SUCCESS';
export const GET_PAGINATED_FAILURE = 'GET_PAGINATED_FAILURE';
export const GET_BOURBON_SUCCESS = 'GET_BOURBON_SUCCESS';
export const GET_BOURBON_FAILURE = 'GET_BOURBON_FAILURE';
export const CLEANUP_BOURBON = 'CLEANUP_BOURBON';

// Review Types
export const GET_BOURBON_REVIEWS_SUCCESS = 'GET_BOURBON_REVIEWS_SUCCESS';
export const GET_BOURBON_REVIEWS_FAILURE = 'GET_BOURBON_REVIEWS_FAILURE';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAILURE = 'CREATE_REVIEW_FAILURE';
export const GET_USER_REVIEWS_SUCCESS = 'GET_USER_REVIEWS_SUCCESS';
export const GET_USER_REVIEWS_FAILURE = 'GET_USER_REVIEWS_FAILURE';
export const CLEANUP_REVIEWS = 'CLEANUP_REVIEWS';
